### ISSUE TITLE
Error in board package

### ISSUE THREAD

**Issue by CptHolzschnauz** [telit/arduino-charlie#6]
I tried to install the new version (thx a bunch for the SDU) on a pristine system on Mac Air M1.
After it went almost thru (Step 5/5) there was a error, probably you have to repack the bag:

Invalid archive: it must contain a single root folder while file cores/def/abi.cpp is outside bootloaders/
java.lang.RuntimeException: java.io.IOException: Invalid archive: it must contain a single root folder while file cores/def/abi.cpp is outside bootloaders/
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:179)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Invalid archive: it must contain a single root folder while file cores/def/abi.cpp is outside bootloaders/
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:180)
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:82)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:162)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Can't find boards.txt in /Users/xyz/Library/Arduino15/packages/Telit-Board/hardware/samd/1.0.2 . Is it from a version befre Arduino 1.5?

Thx for your work!

**Comment by fabiopi-tlt** [comment]
You are right, we fixed the packaging, it should work now.

**Comment by CptHolzschnauz** [comment]
Thx! It works!
